Us020/21 change respondent account status
ONSdigital/ras-party pull request #109
Opened 2018-03-13 13:22 UTC by gemmai95

US020 and US021 add functionality to deactivate and re-activate a respondent's account. This works with changes in backstage and response-operations-ui.

2018-03-13 13:29 UTC, gemmai95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [US021: INT Re-Activate respondents account (L) - Needed for R17](https://trello.com/c/MdXKJfBS/57-us021-int-re-activate-respondents-account-l-needed-for-r17)

2018-03-13 14:35 UTC, andrewmil requested changes
Looks good :+1:

2018-03-13 14:35 UTC, andrewmil commented on ras_party/views/account_view.py
> +@account_view.route('/respondents/edit-account-status', methods=['PUT'])
I think `party_id` should be in the url here rather than being passed in the body of the request

2018-03-13 15:27 UTC, andrewmil approved these changes

2018-03-14 08:49 UTC, gemmai95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [US021: INT Re-Activate respondents account (L) - Needed for R17](https://trello.com/c/MdXKJfBS/57-us021-int-re-activate-respondents-account-l-needed-for-r17)

2018-03-14 10:18 UTC, jcox-dev requested changes
Doc update and potentially handling of missing party.

2018-03-14 10:18 UTC, jcox-dev commented on API.md
> +    "party_id": "438df969-7c9c-4cd4-a89b-ac88cf0bfdf3",
API docs will need amending to show that we're now including the party ID in the URL and not the JSON.

2018-03-14 10:18 UTC, jcox-dev commented on ras_party/controllers/account_controller.py
> +    respondent = query_respondent_by_party_uuid(party_id, session)
Currently if party does not exist this raises a 500 error. Do we need to cover this (and return 404)? (And should we have a test for it?)

2018-03-15 14:01 UTC, tej99 commented on ras_party/views/account_view.py
> +    ras_party.controllers.account_controller.change_respondent_account_status(payload, party_id)
account_controller.change_respondent_account_status(payload, party_id)

2018-03-19 12:44 UTC, jcox-dev approved these changes

2018-03-19 12:57 UTC, tej99 requested changes

2018-03-19 12:57 UTC, tej99 commented on ras_party/controllers/account_controller.py
> +
Are you wanting to return the respondent back from this function? if not the codacy error may need addressing.

2018-03-19 12:58 UTC, gemmai95 commented on ras_party/controllers/account_controller.py
> +
In process of changing this.

2018-03-19 13:05 UTC, tej99 approved these changes

2018-03-20 10:49 UTC, merged