269 ext user account unlock
ONSdigital/ras-party pull request #171
Opened 2018-09-13 09:04 UTC by shahi645

# Motivation and Context
We needed to add an endpoint, which called notify gateway when a respondent first locks his/hers account. The endpoint tells notify to send an email with instructions about resetting and unlocking account.

# What has changed
New endpoint implemented

# How to test?
Run with fronstage PR [https://github.com/ONSdigital/ras-frontstage/pull/396#pullrequestreview-154559006](url)

Then lock your account, should see link appear in party logs, try resetting password and logging back in.

2018-09-18 10:37 UTC, gavinleeedwards requested changes

2018-09-18 10:37 UTC, gavinleeedwards commented on ras_party/controllers/account_controller.py
> +    email_address = respondent.email_address
email_address has already been set once in line 299.

2018-09-18 12:08 UTC, gemmai95 approved these changes

2018-09-20 09:56 UTC, gavinleeedwards approved these changes
All looks good :+1:

2018-09-20 10:01 UTC, shahi645 commented
Don't merge just yet

2018-09-20 13:00 UTC, merged