Replace generic 'RasError' and 'ClientError'
ONSdigital/ras-party pull request #176
Opened 2018-09-25 12:59 UTC by tej99

# Motivation and Context

Nearly every exception raised in this service is a 'RasError' or 'ClientError' exception (which is an extension of RasError).
Every RasError raised was logged at error level and with the message 'Uncaught error'.

# What has changed

I have removed these generic exceptions and replaced them with the appropriate HTTPException.
Logging has also been improved to only have logging at error level when necessary.

# How to test?

Ran integration tests
and AT

# Links

https://trello.com/c/9Fc16htf/279-ras-party-logging-and-exceptions-m

2018-09-25 15:04 UTC, andrewmil requested changes
Looks good, acceptance/unit tests pass

Left a few comments about which exceptions we should be throwing where
Also I think this is a good opportunity to make sure that these exceptions are being tested so probably want to get the test coverage up

2018-09-25 15:04 UTC, andrewmil commented on ras_party/controllers/account_controller.py
> +        logger.debug("No survey bound fo user", party_uuid=party['party_uuid'])
Spelling; `fo` -> `for`

2018-09-25 15:04 UTC, andrewmil commented on ras_party/controllers/account_controller.py
> +from werkzeug.exceptions import InternalServerError, BadRequest, NotFound, Conflict
Imports should be alphabetised

2018-09-25 15:04 UTC, andrewmil commented on ras_party/controllers/account_controller.py
> +        raise BadRequest("There is no survey bound for this user")
I don't understand this check, if we successfully retrieve a collection exercise it will have a survey ID with it.
I think we can remove this whole bit of validation. 

If not then it should be InternalServerError instead

2018-09-25 15:04 UTC, andrewmil commented on ras_party/controllers/account_controller.py
> +        raise NotFound("Could not locate business when creating business association")
This is saying that the party is not found for the business_id from the case that we requested. If we get this error it feels like a InternalServerError instead of 404

2018-09-25 15:04 UTC, andrewmil commented on ras_party/controllers/account_controller.py
> +            raise NotFound("Could not locate business when creating business association")
business_id comes from the case we retrieve here. If this doesn't correspond to a real business there's a problem with our data and I think this should be InternalServerError

2018-09-25 15:04 UTC, andrewmil commented on ras_party/controllers/business_controller.py
> +import logging
logging is in the standard library so should be at the top

2018-09-25 15:04 UTC, andrewmil commented on ras_party/views/business_view.py
> +        logger.info(does_not_exist, reference=ref, url=request.url, status=404)
weird to define this string as a variable here first and to log out the url

2018-09-25 15:04 UTC, andrewmil commented on ras_party/controllers/account_controller.py
> +        logger.debug("No survey bound fo user", party_uuid=party['party_uuid'])
Untested

2018-09-25 15:04 UTC, andrewmil commented on ras_party/controllers/account_controller.py
> +        raise InternalServerError(f"Error updating database for user {party['id']}")
All of these exceptions are untested

2018-09-25 15:04 UTC, andrewmil commented on ras_party/controllers/account_controller.py
> +        logger.error("Unexpected response from auth service, unable to change user password",
Untested

2018-09-25 15:04 UTC, andrewmil commented on ras_party/controllers/account_controller.py
> +        logger.error("Unexpected response from auth service, unable to change user email",
Untested

2018-09-25 15:06 UTC, andrewmil commented on ras_party/error_handlers.py
>      logger.exception('Uncaught exception', status=500)
I think we need to question whether this exception handler is giving us any value, right now it's just catching it and doing nothing with it.

2018-09-26 06:55 UTC, shahi645 commented
Im happy with the changes mostly, just some test coverage needed to be added from @tej99 which andrew has picked up on, then good to get this in

2018-09-26 11:10 UTC, andrewmil commented on ras_party/controllers/party_controller.py
>          respondent = query_respondent_by_party_uuid(id, session)
Untested

2018-09-26 11:10 UTC, andrewmil commented on ras_party/controllers/party_controller.py
> +            logger.debug("Business with id does not exist", business_id=id, status=404)
Untested

2018-09-26 11:57 UTC, andrewmil approved these changes
There's still a couple of points that aren't tested but acceptance tests are passing and test coverage has been bumped up significantly so good to go I think :+1:

2018-09-26 12:12 UTC, merged