Add models & break cyclic dependency between model and ONSEnvironment
ONSdigital/ras-party pull request #2
Opened 2017-05-31 10:30 UTC by jonmorphic

2017-06-01 08:35 UTC, LJBabbage requested changes
LGTM, bar a couple of minor changes

2017-06-01 08:35 UTC, LJBabbage commented on README.md
> +database via create_db.py. Run `python create_db.py` in the project root to see further guidance.
python create_db.py needs changing now

2017-06-01 08:35 UTC, LJBabbage commented on swagger_server/database.py
> +    from swagger_server.models_local import _model
As discussed one of these needs to change, ref line 33

2017-06-02 09:16 UTC, jonmorphic commented on swagger_server/database.py
> +    from swagger_server.models_local import _model
Fixed. This is likely to change again in a subsequent PR as ras-party-v2 drifts away from code generator.

2017-06-02 09:27 UTC, LJBabbage approved these changes

2017-06-02 09:27 UTC, merged