Added rollbacks and the use of sub transactions
ONSdigital/ras-party pull request #201
Opened 2019-08-15 13:02 UTC by AndrewTorrance

# Motivation and Context
If auth registration failed on add new user then the records where left in the party service.
Added sub transactions so that roll back can be added on auth registration fail

# What has changed
removed @transaction , this was an app level transaction not db transaction and was not used
Added sub transactions so that we can roll back to specific points

# How to test?
run unit and acceptance tests . A difficult one to test manually.

# Links
https://trello.com/c/UtaGbEk1

2019-08-15 13:14 UTC, mfcrocker approved these changes

2019-08-16 14:34 UTC, insacuri requested changes

2019-08-16 14:34 UTC, insacuri commented on ras_party/controllers/account_controller.py
> +        logger.error('Party service db post respondent caused exception', party_uuid=translated_party['party_uuid'],
You can rewrite this bit to 
```
except Exception:
    logger.exception('Party service db post respondent caused exception', party_uuid=translated_party['party_uuid'])
    raise
```

I'd also say whilst it's fresh in your head, can we have more specific exceptions instead of the top level `Exception` so we have a better idea what can go wrong down the line.

2019-08-21 09:37 UTC, insacuri requested changes

2019-08-21 09:37 UTC, insacuri commented on ras_party/controllers/account_controller.py
> +    The Contxet manager commits to session, If db fails after that and before main commit then db state is unknown
Typo in comment

2019-08-21 09:37 UTC, insacuri commented on ras_party/controllers/account_controller.py
> +    except Exception as exception:
Can we have this work for all the specific exceptions instead of just the generic exception?

2019-08-21 09:37 UTC, insacuri commented on ras_party/controllers/account_controller.py
> +        session.commit()  # Full session commit
Can we get a comment either here or at the top that acknowledges that if this commit fails then we're going to be in a half complete state that we'll just have to handle on the rare case by case basis.
Either that or handle this unlikely (but possible) issue?

2019-08-21 09:48 UTC, necrophonic commented on ras_party/controllers/account_controller.py
> +            logger.info('Registering respondent auth service responded with', status=oauth_response.status_code,
Should probably be an `error` rather than an `info` as it's unexpected

2019-08-21 09:48 UTC, necrophonic commented on ras_party/controllers/account_controller.py
> +        logger.error('Party service db post respondent caused exception', party_uuid=translated_party['party_uuid'],
I'd also write it maybe more like: "Exception occurred while attempting to enrol new user" - we'll know it's the party service et al from the metadata that'll be attached to the logs

2019-08-21 10:27 UTC, insacuri approved these changes

2019-08-21 12:23 UTC, merged