User account creation email change
ONSdigital/ras-party pull request #309
Opened 2021-02-04 16:48 UTC by akssinhaamit

# Motivation and Context

# What has changed

# How to test?

# Links

2021-02-08 13:00 UTC, insacuri requested changes

2021-02-08 13:00 UTC, insacuri commented on _infra/helm/party/templates/deployment.yaml
> +          - name: NOTIFY_VERIFY_ACCOUNT_EMAIL_CHANGE
These 2 variables need to have `_TEMPLATE` at the end.  Update in here and every occurrence in the PR

2021-02-08 13:00 UTC, insacuri commented on _infra/helm/party/values.yaml
> +  enabled: true
are you sure we should be changing this?

2021-02-08 13:00 UTC, insacuri commented on config.py
> +    NOTIFY_VERIFY_ACCOUNT_EMAIL_CHANGE = os.getenv('NOTIFY_VERIFY_ACCOUNT_EMAIL_CHANGE',
Previous comment about `_TEMPLATE` suffix applies here too

2021-02-08 13:00 UTC, insacuri commented on config.py
> +    SEND_EMAIL_TO_GOV_NOTIFY = _is_true(os.getenv('SEND_EMAIL_TO_GOV_NOTIFY', True))
As with the previous comment, are you sure you want to be changing this?

2021-02-08 13:00 UTC, insacuri commented on ras_party/views/account_view.py
> +    return make_response(jsonify(response), 200)
This can be rewritten to `return jsonify(response)`.  The `make_response` and the explicit 200 isn't needed

2021-02-10 11:40 UTC, akssinhaamit commented on _infra/helm/party/values.yaml
> +  enabled: true
yes - wanted to make sure dev cluster actually sends the test email for testing and mimic the actual flow :-)

2021-02-10 11:41 UTC, akssinhaamit commented on config.py
> +    SEND_EMAIL_TO_GOV_NOTIFY = _is_true(os.getenv('SEND_EMAIL_TO_GOV_NOTIFY', True))
yes - wanted to make sure dev cluster actually sends the test email for testing and mimic the actual flow :-)

2021-02-10 12:01 UTC, akssinhaamit commented on _infra/helm/party/templates/deployment.yaml
> +          - name: NOTIFY_VERIFY_ACCOUNT_EMAIL_CHANGE
👍

2021-02-10 12:01 UTC, akssinhaamit commented on _infra/helm/party/templates/deployment.yaml
> +          - name: NOTIFY_VERIFY_ACCOUNT_EMAIL_CHANGE
👍

2021-02-10 12:01 UTC, akssinhaamit commented on _infra/helm/party/values.yaml
> +  enabled: true
👍

2021-02-10 12:01 UTC, akssinhaamit commented on config.py
> +    NOTIFY_VERIFY_ACCOUNT_EMAIL_CHANGE = os.getenv('NOTIFY_VERIFY_ACCOUNT_EMAIL_CHANGE',
👍

2021-02-10 12:04 UTC, akssinhaamit commented on ras_party/views/account_view.py
> +    return make_response(jsonify(response), 200)
followed the same pattern used as others

2021-02-10 16:26 UTC, insacuri approved these changes

2021-02-10 16:57 UTC, merged