Setup party to check verification tokens used in email are valid
ONSdigital/ras-party pull request #364
Opened 2022-03-10 13:00 UTC by arroyoAle

# What and why?
Setup party to check verification tokens used in email are valid. For now it is for the reset password email and can be used for others in future
# How to test?

# Trello

2022-03-15 14:13 UTC, insacuri commented on ras_party/models/models.py
> +    verification_tokens = Column(ARRAY(Text))
You can have multiple tokens live at once?  That seems kinda weird to me

2022-03-15 14:18 UTC, mfcrocker requested changes
I don't believe this has been implemented in a way that adheres to RESTful principles. A `PUT` should replace the resource on the server with the one provided in the body - the endpoint that's been created here is a mashup between a `POST` and a `DELETE` depending on whether the verification token is already stored.

The endpoint is also not really named in a way that references resources (which is probably an indication that something isn't properly RESTful).

Thankfully, this shouldn't be too difficult to fix and just needs us to split things in a slightly different way. I'd suggest 2 endpoints (on top of having verification tokens returned in the GET respondent by email endpoint):

`POST /respondents/{respondent_uuid}/verification_tokens`

`{
   "token": "<token>"
}`

This would add a verification token to a user

`DELETE /respondents/{respondent_uuid}/verification_tokens/{token}`

This would remove a verification token from a user

All in all this is good work and you can almost certainly keep most of the code here, but I think we should be striving to keep our APIs clean and compliant with REST principles where possible (and rethinking what we're doing if we can't do that).

2022-03-15 14:28 UTC, insacuri commented on ras_party/models/models.py
> +    verification_tokens = Column(ARRAY(Text))
Also this column name doesn't seem all that descriptive for me.  The token we're putting in this column today is for password reset only right?  The current name implies you can put tokens for whatever verification purpose in here which doesn't feel right

2022-03-18 15:03 UTC, mfcrocker approved these changes
Looks good, 1 tiny thing

2022-03-18 15:03 UTC, mfcrocker commented on ras_party/controllers/account_controller.py
> +        raise NotFound("Verification token not received")
This would be a 400 Bad Request

```suggestion
        raise BadRequest("Verification token not received")
```

2022-03-18 15:39 UTC, merged