Apply restrictions to forgotten password journey.
ONSdigital/ras-party pull request #367
Opened 2022-04-06 08:47 UTC by arroyoAle

# What and why?
Set up party to allow restrictions on amount of password reset attempts
# How to test?

# Trello

2022-04-12 12:02 UTC, creativeappdevamit approved these changes

2022-04-21 09:42 UTC, anwilkie commented
/deploy wilkia

2022-04-21 10:37 UTC, insacuri commented on API.md
> +  "counter": <counter>
Needs quotes around the <counter> for it to be valid json

2022-04-21 10:43 UTC, insacuri requested changes
A few small comments and one design question, but overall it looks good

2022-04-21 10:43 UTC, insacuri commented on API.md
> +* `PUT /party-api/v1/respondents/<respondent_id>/password-reset-counter`
Why do you need this?  If a user attempts to get a password reset email then it should just increment itself without something external telling it to increment.  Or am I missing something?

2022-04-21 10:43 UTC, insacuri commented on ras_party/views/account_view.py
> +    return make_response(jsonify({"counter": counter}), 200)
for all of these simple endpoints that have 200 return values , doing:
```python
return jsonify(<insert dict here>)
```
will suffice.

I think (but you'll have to check... maybe in this repo or collection instrument?) you can do the same for a non-200 value, where it looks something like:
```python
return jsonify(<insert dict here>), 400
```

2022-04-21 10:50 UTC, insacuri commented on ras_party/views/account_view.py
> +@account_view.route("/respondents/<respondent_id>/password-verification-token", methods=["POST"])
For the future, doing it this way is naughty, but I don't think it's a huge deal for this bit of work.
If you change the name of url in 2 services without allowing for backwards compatability (in this case, allowing for `-tokens` AND `-token`) then there will be a non-0 amount of time where the bit of functionality won't work.

For this one it's acceptable becuase it's for something that isn't constantly in use and will only stop working for a second.  But be more considerate in future as this'll bite you if it's a more core bit of functionality.

2022-04-21 11:00 UTC, insacuri commented on ras_party/views/account_view.py
> +@account_view.route("/respondents/<respondent_id>/password-verification-token", methods=["POST"])
For this one and the other one, can you add the old version as a route above it:

```python
@account_view.route("/respondents/<respondent_id>/password-verification-token", methods=["POST"])
@account_view.route("/respondents/<respondent_id>/password-verification-tokens", methods=["POST"])
def ....():
```
Put a comment somewhere around it that the `-tokens` route is deprecated
Also update the API documentation with the old route and also mention that it's deprecated.

2022-04-22 08:54 UTC, insacuri approved these changes

2022-04-22 10:57 UTC, merged