Split logic for loading new/existing businesses
ONSdigital/ras-party pull request #88
Opened 2017-12-22 11:12 UTC by tej99

Fixing a bug where uploading an existing business removed all pervious business_attributes relations.

2017-12-22 11:41 UTC, jcox-dev requested changes
Looks good but probably need to add tests for the new method.

2017-12-22 11:41 UTC, jcox-dev commented on ras_party/models/models.py
> +    def add_versioned_attributes(self, party):
We should have a test for this new method.

2017-12-22 11:41 UTC, jcox-dev commented on ras_party/controllers/business_controller.py
> +    if business:
This is a lot clearer 👍

2018-01-04 14:19 UTC, jcox-dev approved these changes

2018-01-04 14:21 UTC, andrewmil approved these changes
Tested by hitting endpoints locally, everything looks good :+1:

2018-01-04 14:22 UTC, merged