Updates for running with 0.3 API GW
ONSdigital/ras-party pull request #9
Opened 2017-06-21 10:00 UTC by oddjobz

This introduced dependencies based on the new common code but in particular on the API GW. This version needs to run against an 0.3+ version of the GW.

2017-06-22 06:48 UTC, jonmorphic requested changes
Looks straightforward, just a possible typo in demo section.

2017-06-22 06:48 UTC, jonmorphic commented on config.ini
> +pi_protocol = https
Typo here?

2017-06-22 09:19 UTC, jonmorphic commented
A further comment on this, but one to deal with out-of-band of this PR. How can I tell which is the latest stable version of ras-common? This branch pulls from a feature branch version, is that what you intended?

2017-06-23 09:06 UTC, oddjobz commented
Ok, fixed typo, and have changed the requirements.txt .. branching obviously subject to some dicussion but for now it's tagged to the 'release' branch.

2017-06-23 15:05 UTC, jonmorphic approved these changes

2017-06-23 15:25 UTC, jonmorphic commented
I did approve these changes on the basis the tests pass for me. However, I'm unsure where the syntax has come from for the ons-ras-common requirement, as it looks incorrect on closer inspection. It's going to pull from the head of the release/0.3 branch. I've gone down the requirements-from-git path before and it ended up a mess. I suspect tagging the version is the best we can do right now until a PyPI host can be setup.

2017-06-26 11:02 UTC, closed without merging